//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MOX_IT
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vuelo
    {
        public int ID { get; set; }
        public Nullable<System.DateTime> HorarioLlegada { get; set; }
        public Nullable<bool> Demorado { get; set; }
        public int IDLineaAerea { get; set; }
        public string NumeroDeVuelo { get; set; }

        public virtual LineaAerea LineaAerea { get; set; }
    }
}
